; NEXA CONFIG
[General]
Port=3551
DevelopmentServerPort=3000

[MatchMakerService]
GameServerIp=127.0.0.1:7777
MatchMakerIp=ws://127.0.0.1:80

[TimeLine]
; Can be 2, 3, or 4 | SEASON OG STAGES (27.11)
RufusStage=4

; TMNT STAGES (28.30) | VALUE SHOULD BE 1 - 3
TMNTStage=3 ; SOON

; ATLA ICEBERG STAGES (29.xx OR  29.20+) | VALUE SHOULD BE 1 - 3
AtlaIcebergStage=3 ; SOON

; WATERLEVEL C2 S3 (13.40) | VALUE SHOULD BE 1 - 7
WaterLevel=1

; Enable Water storm (v12.61)
WaterStorm=true

[Fortnite] ; SOON
RoatateShop=true ; if you use this it will ask (Y/N) in pormp to rotate the shop
RoatateAskSkipTime=30 ; Time in seconds before asking to rotate the shop again if the user said no to rotating the shop
AutoRotateShop=false ; if u use this turn of the above one, this will rotate the shop every X hours based on the value below
AutoRotateShopTime=2 ; In hours

; for new accounts, how much vbucks, level, and gold they should start with
StarterVB=13500
StarterLevel=1
StarterGoldAmmount=5000

;Custom Lobby Background
custom_background = false
image_url="https://cdn2.unrealengine.com/t-background-darkblue-2048x1024-4b5228ccabe2.png"




# TODO
; add the [Fortnite] section to the configs and its functions
; add the custom lobby background function
; add  all new timeline satges and configs